import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { PlanProvider } from "@/context/PlanContext";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${inter.variable} font-sans`}>
        <PlanProvider>
          <div className="flex min-h-screen flex-col">
            <Navbar />
            <main className="w-full flex-1">{children}</main>
            <Footer />
          </div>

          <ToastContainer
            position="top-right"
            autoClose={2500}
            theme="dark"
            newestOnTop
            closeOnClick
            pauseOnHover
          />
        </PlanProvider>
      </body>
    </html>
  );
}
