import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

const oswald = Oswald({
  subsets: ["latin"],
  variable: "--font-oswald",
  display: "swap",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Fit Log",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
     <html lang="en">
      <body
        className={`${oswald.variable} ${inter.variable} font-sans`}
      >
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="w-full flex-1">
            {children}
          </main>
          <Footer/>
        </div>
      </body>
    </html>
  );
}
